version: "3"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432

    app:
        build: .
        command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        depends_on:
            - postgres